### PR TITLE
Add bash to container

### PR DESCRIPTION
**Pull request by arubacao**
This enables the workaround method to execute multiple commands within the docker-compose.yml.
http://stackoverflow.com/a/30064175/3576892

In my case:
`command: bash -c "aws --endpoint-url=http://192.168.99.100:9002 s3api create-bucket --bucket first-bucket && aws --endpoint-url=http://192.168.99.100:9002 s3api create-bucket --bucket second-bucket"`

cheers

### CODE REVIEW

**Comment by sekka1** [comment]
How big is the container after this?  Wanted to keep it small.

**Comment by arubacao** [comment]
```
aws-cli-docker/test       latest              f73273acc95b        About a minute ago   92.66 MB
garland/aws-cli-docker    latest              ecd19759c3d5        3 weeks ago          89.38 MB
```

not even 5MB difference 👍

**Comment by sekka1** [comment]
Without installing bash i can do this and run multiple commands.

```
$ docker run garland/aws-cli-docker sh -c "echo one; echo two"
one
two
```

Does this solve your use case?

**Comment by arubacao** [comment]
Yep works for me, thx

**Pull request closed without merging**
